services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node main.js
    restart: always
    networks:
      - node-network
    volumes:
     - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: nginx
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge